### ISSUE TITLE
How to get Public Key

### ISSUE THREAD

**Issue by Swaggadan** [Zilliqa/gozilliqa-sdk#11]
Following the example to create a transaction, the public key needs to be a string. How do I get that to use in createTransaction?

`wallet := NewWallet()
	wallet.AddByPrivateKey("e19d05c5452598e24caad4a0d85a49146f7be089515c905ae6a19e8a578a6930")
wallet.DefaultAccount.PublicKey`

wallet.DefaultAccount.PublicKey is a unit8 but 

`&transaction.Transaction{
SenderPubKey : wallet.DefaultAccount.PublicKey`

requires a string

**Comment by renlulu** [comment]
Hey, you can use `util.EncodeHex` to encode this byte array to hex string.

**Comment by Swaggadan** [comment]
Thanks, that worked.
