### ISSUE TITLE
Transactions

### ISSUE THREAD

**Issue by Swaggadan** [Zilliqa/gozilliqa-sdk#12]
Is there anyway to send Zil, instead of Qa using transaction.Transaction.Amount?

![image](https://user-images.githubusercontent.com/137142/71413138-30a63380-2627-11ea-9fd0-2175bbba8852.png)

Also `tx.Confirm` returns nothing. Using `tx.Status` after `tx,Confirm` should let me know if the trans was successful or not right?

**Comment by renlulu** [comment]
The unit inside a transaction is always qa, but you can use `util.FromQa` to do the conversion. For 2th, the answer is YES.

**Comment by Swaggadan** [comment]
Thanks. After some reading, I understand now that `Qa` is a unit for Zil. Lastly, since `transaction amount` needs a `string`, this is good enough 
`strconv.FormatFloat(util.ToQa(value, 0), 'f', -1, 64)`
