### ISSUE TITLE
Support payment transfer from one account to multiple accounts

### ISSUE THREAD

**Issue by renlulu** [Zilliqa/gozilliqa-sdk#22]

**Comment by Swaggadan** [comment]
Any update to this?

**Comment by renlulu** [comment]
Hey, take a look at this https://github.com/Zilliqa/gozilliqa-sdk/blob/master/account/wallet_test.go#L87 @Swaggadan

**Comment by Swaggadan** [comment]
Thanks

**Comment by renlulu** [comment]
I'll close this! Let me know if you have any other feedback or issue! Thanks!
