### ISSUE TITLE
Q: How to get tx hash(aka txid) by transaction param?

### ISSUE THREAD

**Issue by islishude** [Zilliqa/gozilliqa-sdk#35]

**Comment by Swaggadan** [comment]
In the [ReadME Send Transaction](https://github.com/Zilliqa/gozilliqa-sdk#send-a-transfer-transaction) you can get txid from 
```
result := rsp.Result.(map[string]interface{})
hash := result["TranID"].(string)
```

**Comment by islishude** [comment]
how to get it without sending to rpc?

**Comment by islishude** [comment]
I got it!

`tx_hash = sha256(encoded_tx)`
