### ISSUE TITLE
Provider APIs return nil, nil when rpc call failed

### ISSUE THREAD

**Issue by deepgully** [Zilliqa/gozilliqa-sdk#57]
GetNetworkId,  GetBlockchainInfo,  GetShardingStructure,  GetDsBlock,  GetLatestDsBlock,  GetNumDSBlocks,  GetSmartContractSubState

https://github.com/Zilliqa/gozilliqa-sdk/blob/a761345d152e2e6ffce7e44dc516ff8fd2f477a0/provider/provider.go#L744-L749

**Comment by renlulu** [comment]
PR merged to master.
