### ISSUE TITLE
wrong method name of GetPendingTxns 

### ISSUE THREAD

**Issue by deepgully** [Zilliqa/gozilliqa-sdk#60]
the method name should be "GetPendingTxns" instead of "GetPendingTxn"

https://github.com/Zilliqa/gozilliqa-sdk/blob/d6170e44ec0a3759113504eddaa38f023df8ca56/provider/provider.go#L490-L494

**Comment by renlulu** [comment]
Thanks! By the way, I think at this stage, the response of it can be more concrete.
