### ISSUE TITLE
program crashed due to GetEventReceiptTask got a nil pointer return when calling function GetTransaction of provider

### ISSUE THREAD

**Issue by sportsminer** [Zilliqa/gozilliqa-sdk#78]
**Describe the bug**
program crashed due to GetEventReceiptTask got a nil pointer return when calling function GetTransaction of provider，
GetTransaction  will return nil pointer for tnx sometime, and GetEventReceiptTask did not check such result and using the nil pointer，so it will let the program crashed due to SIGSEGV exception signal.

**To Reproduce**
run 	walker.StartTraversalBlock() for a period time

**Expected behavior**
walk through from block to to block

**Screenshots**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8f8a2a]

goroutine 47629 [running]:
github.com/Zilliqa/gozilliqa-sdk/subscription.GetEventReceiptTask.Run(0xc000275780, 0xc00012f180, 0x40, 0xc0003594c0, 0xc0007e9720, 0xdb525)
        /Users/shiyong/go/pkg/mod/github.com/!zilliqa/gozilliqa-sdk@v1.2.0/subscription/chainwalker.go:92 +0xca
github.com/Zilliqa/gozilliqa-sdk/workpool.(*WorkerPool).Poll.func1(0xc0007e93b0, 0xc08d40, 0xc000443dd0, 0xc00002c230)
        /Users/shiyong/go/pkg/mod/github.com/!zilliqa/gozilliqa-sdk@v1.2.0/workpool/workpool.go:79 +0x6a
created by github.com/Zilliqa/gozilliqa-sdk/workpool.(*WorkerPool).Poll
        /Users/shiyong/go/pkg/mod/github.com/!zilliqa/gozilliqa-sdk@v1.2.0/workpool/workpool.go:77 +0x65

**Desktop (please complete the following information):**
 - OS: [macos]
 - Version [11]

**Comment by dantudor** [comment]
This issue is due to api.zilliqa.com returning a HTML cloudflare 502 bad gateway error.

Is there a rate limiter on api.zilliqa.com?

```
 rpc call GetTransaction() on https://api.zilliqa.com/ status code: 502. could not decode body to rpc response: invalid character '<' looking for beginning of value
```

![image](https://user-images.githubusercontent.com/1281127/124511431-0281e200-ddce-11eb-9bbd-81628daaf16f.png)

**Comment by noel-yoo** [comment]
https://github.com/Zilliqa/Zilliqa/releases/tag/v8.1.1
> This hot-fix addresses 502 error network issue observed intermittently on staking raw endpoint by some SSN operators. (#2707)
