### ISSUE TITLE
err: -8:Gas limit (1) lower than minimum for payment transaction (50)

### ISSUE THREAD

**Issue by hoangphuongcs** [Zilliqa/gozilliqa-sdk#93]
Hi, now I got an error when sending: "-8:Gas limit (1) lower than minimum for payment transaction (50)"
It hasn't happened before. Please help me to check. 
Code send:
```
...
gasPrice := zs.provider.GetMinimumGasPrice().Result.(string)
...
tx := &transaction.Transaction{
		Version:  version,
		ToAddr:   toAddress,
		Amount:   amount,
		GasPrice: gasPrice,
		GasLimit: "1",
		Code:     "",
		Data:     "",
		Priority: false,
	}
```

**Comment by teye** [comment]
Hi, for payment transaction, the minimum gas limit is 50 instead of 1. This is a new change after the blockchain is updated last week.

Refer to this for more info:
https://dev.zilliqa.com/docs/dev/dev-upgrade-v8/#3-payment-transaction-gas-unit-increase-from-1-to-50
